#!/bin/bash

set -e

rm -rf build dist
source venv/bin/activate

echo Upping version..
python up_version.py

pip install --upgrade pip setuptools wheel twine
python setup.py sdist bdist_wheel
twine upload dist/*

exit

echo ""
echo Building...
python -m build


echo ""
echo Uploading...
python -m twine upload --verbose --repository  pypi dist/*

sleep 10
pip install --upgrade hyperp
